version: "3.4"

services:
  cachenginx:
    image: ${DOCKER_REGISTRY-}cachenginx #nginx:latest
    container_name: cachenginx
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    #volumes:
    #  - ./conf.d:/etc/nginx/conf.d