version: "3.4"

services:
  cachenginx:
    image: ${DOCKER_REGISTRY-}cachenginx #nginx:latest
    container_name: cachenginx
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    #volumes:
    #  - ./conf.d:/etc/nginx/conf.d
  ataaofapi:
    image: ${DOCKER_REGISTRY-}ataaofapi
    container_name: ataaofapi
    build:
      context: ../ATAAOF_App/
      dockerfile: Dockerfile
    ports:
      - 5105:5105